#!/usr/bin/env python3
"""Generate a hash-pinned requirements lock from a local wheelhouse.

Scans a directory of downloaded distributions (wheels and/or sdists) and writes
a ``requirements.lock`` where every package is pinned to an exact version and
one or more ``--hash=sha256:...`` values. Installing with ``--require-hashes``
then refuses anything whose bytes don't match - the supply-chain guard the repo
relies on (see docs/development.md).

Usage:
    python scripts/_gen_lock.py <wheelhouse_dir> <output_lock_path>

This is a maintainer helper invoked by scripts/lock-deps.sh; it is not imported
by the application.
"""

from __future__ import annotations

import hashlib
import sys
from collections import defaultdict
from pathlib import Path

from packaging.utils import (
    canonicalize_name,
    parse_sdist_filename,
    parse_wheel_filename,
)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _name_version(path: Path) -> tuple[str, str]:
    if path.name.endswith(".whl"):
        name, version, _build, _tags = parse_wheel_filename(path.name)
        return canonicalize_name(name), str(version)
    if path.name.endswith((".tar.gz", ".zip")):
        name, version = parse_sdist_filename(path.name)
        return canonicalize_name(name), str(version)
    raise ValueError(f"unrecognized distribution file: {path.name}")


def generate(wheelhouse: Path, out_path: Path) -> int:
    files = sorted(
        p
        for p in wheelhouse.iterdir()
        if p.suffix in {".whl", ".zip"} or p.name.endswith(".tar.gz")
    )
    if not files:
        print(f"error: no distributions found in {wheelhouse}", file=sys.stderr)
        return 1

    # name -> {version -> set(hashes)}; multiple wheels per package (e.g. one
    # per platform) collapse into multiple hashes under one pinned version.
    pinned: dict[str, dict[str, set[str]]] = defaultdict(lambda: defaultdict(set))
    for path in files:
        name, version = _name_version(path)
        pinned[name][version].add(_sha256(path))

    lines: list[str] = [
        "# AUTO-GENERATED by scripts/lock-deps.sh - do not edit by hand.",
        "# Exact, hash-pinned dependencies for reproducible, offline, tamper-",
        "# evident installs. Regenerate only when intentionally bumping versions.",
        "# Install with:",
        "#   pip install --require-hashes -r requirements.lock \\",
        "#       --no-index --find-links vendor/wheels",
        "",
    ]
    for name in sorted(pinned):
        versions = pinned[name]
        if len(versions) > 1:
            joined = ", ".join(sorted(versions))
            print(
                f"error: {name} has multiple versions in the wheelhouse: {joined}",
                file=sys.stderr,
            )
            return 1
        version, hashes = next(iter(versions.items()))
        hash_args = " \\\n    ".join(f"--hash=sha256:{h}" for h in sorted(hashes))
        lines.append(f"{name}=={version} \\\n    {hash_args}")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(pinned)} packages, {len(files)} files).")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    return generate(Path(argv[0]).resolve(), Path(argv[1]).resolve())


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
